[2025-09-05T20:27:12.817+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_mysql_demo.create_table manual__2025-09-05T20:27:11.377789+00:00 [queued]>
[2025-09-05T20:27:12.836+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_mysql_demo.create_table manual__2025-09-05T20:27:11.377789+00:00 [queued]>
[2025-09-05T20:27:12.836+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-09-05T20:27:12.858+0000] {taskinstance.py:1350} INFO - Executing <Task(MySqlOperator): create_table> on 2025-09-05 20:27:11.377789+00:00
[2025-09-05T20:27:12.867+0000] {standard_task_runner.py:57} INFO - Started process 97 to run task
[2025-09-05T20:27:12.873+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_mysql_demo', 'create_table', 'manual__2025-09-05T20:27:11.377789+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/crea_tablas.py', '--cfg-path', '/tmp/tmpd8sy8h_t']
[2025-09-05T20:27:12.874+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask create_table
[2025-09-05T20:27:12.955+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_mysql_demo.create_table manual__2025-09-05T20:27:11.377789+00:00 [running]> on host 50437ce15fe5
[2025-09-05T20:27:13.092+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_mysql_demo' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-09-05T20:27:11.377789+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-05T20:27:11.377789+00:00'
[2025-09-05T20:27:13.093+0000] {sql.py:262} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS empleados (
            id INT AUTO_INCREMENT PRIMARY KEY,
            nombre VARCHAR(100),
            cargo VARCHAR(100),
            fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        
[2025-09-05T20:27:13.112+0000] {base.py:73} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-09-05T20:27:13.235+0000] {base.py:73} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-09-05T20:27:13.267+0000] {sql.py:375} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS empleados (
            id INT AUTO_INCREMENT PRIMARY KEY,
            nombre VARCHAR(100),
            cargo VARCHAR(100),
            fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        , parameters: None
[2025-09-05T20:27:13.330+0000] {sql.py:384} INFO - Rows affected: 0
[2025-09-05T20:27:13.362+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=dag_mysql_demo, task_id=create_table, execution_date=20250905T202711, start_date=20250905T202712, end_date=20250905T202713
[2025-09-05T20:27:13.414+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-09-05T20:27:13.447+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
