[2025-09-06T05:39:09.466+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_insert_select.test manual__2025-09-06T05:38:45.486954+00:00 [queued]>
[2025-09-06T05:39:09.481+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_insert_select.test manual__2025-09-06T05:38:45.486954+00:00 [queued]>
[2025-09-06T05:39:09.481+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-09-06T05:39:09.503+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): test> on 2025-09-06 05:38:45.486954+00:00
[2025-09-06T05:39:09.515+0000] {standard_task_runner.py:57} INFO - Started process 1951 to run task
[2025-09-06T05:39:09.520+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mysql_insert_select', 'test', 'manual__2025-09-06T05:38:45.486954+00:00', '--job-id', '326', '--raw', '--subdir', 'DAGS_FOLDER/mysql_insert_select.py', '--cfg-path', '/tmp/tmpfl14sduz']
[2025-09-06T05:39:09.524+0000] {standard_task_runner.py:85} INFO - Job 326: Subtask test
[2025-09-06T05:39:09.615+0000] {task_command.py:410} INFO - Running <TaskInstance: mysql_insert_select.test manual__2025-09-06T05:38:45.486954+00:00 [running]> on host 6faa580ba6cb
[2025-09-06T05:39:09.753+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_insert_select' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T05:38:45.486954+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T05:38:45.486954+00:00'
[2025-09-06T05:39:09.757+0000] {logging_mixin.py:149} INFO - <class 'sklearn.neighbors._classification.KNeighborsClassifier'>
[2025-09-06T05:39:09.758+0000] {logging_mixin.py:149} INFO - Modelo cargado correctamente: <class 'sklearn.neighbors._classification.KNeighborsClassifier'>
[2025-09-06T05:39:09.759+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"

[2025-09-06T05:39:09.762+0000] {logging_mixin.py:149} INFO - Predicci√≥n de prueba: [1]
[2025-09-06T05:39:09.762+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-09-06T05:39:09.776+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=mysql_insert_select, task_id=test, execution_date=20250906T053845, start_date=20250906T053909, end_date=20250906T053909
[2025-09-06T05:39:09.819+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-09-06T05:39:09.859+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
