[2025-09-06T04:58:43.101+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_insert_select.train_model manual__2025-09-06T04:58:29.030575+00:00 [queued]>
[2025-09-06T04:58:43.116+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_insert_select.train_model manual__2025-09-06T04:58:29.030575+00:00 [queued]>
[2025-09-06T04:58:43.116+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-09-06T04:58:43.136+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): train_model> on 2025-09-06 04:58:29.030575+00:00
[2025-09-06T04:58:43.149+0000] {standard_task_runner.py:57} INFO - Started process 936 to run task
[2025-09-06T04:58:43.160+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mysql_insert_select', 'train_model', 'manual__2025-09-06T04:58:29.030575+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/mysql_insert_select.py', '--cfg-path', '/tmp/tmpkol_x0eo']
[2025-09-06T04:58:43.164+0000] {standard_task_runner.py:85} INFO - Job 241: Subtask train_model
[2025-09-06T04:58:43.249+0000] {task_command.py:410} INFO - Running <TaskInstance: mysql_insert_select.train_model manual__2025-09-06T04:58:29.030575+00:00 [running]> on host 6faa580ba6cb
[2025-09-06T04:58:43.409+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_insert_select' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T04:58:29.030575+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T04:58:29.030575+00:00'
[2025-09-06T04:58:43.432+0000] {base.py:73} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-09-06T04:58:43.720+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

[2025-09-06T04:58:43.723+0000] {logging_mixin.py:149} INFO - Accuracy: 0.99
[2025-09-06T04:58:43.723+0000] {logging_mixin.py:149} INFO - Classification Report:
[2025-09-06T04:58:43.727+0000] {logging_mixin.py:149} INFO -               precision    recall  f1-score   support

           1       1.00      0.97      0.98        29
           2       0.93      1.00      0.97        14
           3       1.00      1.00      1.00        24

    accuracy                           0.99        67
   macro avg       0.98      0.99      0.98        67
weighted avg       0.99      0.99      0.99        67
[2025-09-06T04:58:43.730+0000] {logging_mixin.py:149} INFO - Model saved as /opt/***/models/LogisticRegressionModel.pkl
[2025-09-06T04:58:43.731+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-09-06T04:58:43.749+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=mysql_insert_select, task_id=train_model, execution_date=20250906T045829, start_date=20250906T045843, end_date=20250906T045843
[2025-09-06T04:58:43.807+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-09-06T04:58:43.861+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
