[2025-09-06T05:38:48.258+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_insert_select.validate_model manual__2025-09-06T05:38:45.486954+00:00 [queued]>
[2025-09-06T05:38:48.280+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_insert_select.validate_model manual__2025-09-06T05:38:45.486954+00:00 [queued]>
[2025-09-06T05:38:48.281+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-09-06T05:38:48.311+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): validate_model> on 2025-09-06 05:38:45.486954+00:00
[2025-09-06T05:38:48.324+0000] {standard_task_runner.py:57} INFO - Started process 1904 to run task
[2025-09-06T05:38:48.331+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mysql_insert_select', 'validate_model', 'manual__2025-09-06T05:38:45.486954+00:00', '--job-id', '315', '--raw', '--subdir', 'DAGS_FOLDER/mysql_insert_select.py', '--cfg-path', '/tmp/tmpgzb7whvm']
[2025-09-06T05:38:48.334+0000] {standard_task_runner.py:85} INFO - Job 315: Subtask validate_model
[2025-09-06T05:38:48.415+0000] {task_command.py:410} INFO - Running <TaskInstance: mysql_insert_select.validate_model manual__2025-09-06T05:38:45.486954+00:00 [running]> on host 6faa580ba6cb
[2025-09-06T05:38:48.591+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_insert_select' AIRFLOW_CTX_TASK_ID='validate_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T05:38:45.486954+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T05:38:45.486954+00:00'
[2025-09-06T05:38:48.593+0000] {logging_mixin.py:149} INFO - ✅ Modelo cargado correctamente
[2025-09-06T05:38:48.593+0000] {logging_mixin.py:149} INFO -    - Tipo: <class 'numpy.ndarray'>
[2025-09-06T05:38:48.594+0000] {logging_mixin.py:149} INFO -    - Características esperadas: No disponible
[2025-09-06T05:38:48.594+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-09-06T05:38:48.617+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=mysql_insert_select, task_id=validate_model, execution_date=20250906T053845, start_date=20250906T053848, end_date=20250906T053848
[2025-09-06T05:38:48.670+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-09-06T05:38:48.699+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
